In [1]:
print("hello world")

hello world


In [2]:
import numpy as np
import pandas as pd

# Create and print a matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr,"mean:", arr.mean(), "std:", arr.std())

[1 2 3 4 5] mean: 3.0 std: 1.4142135623730951


In [1]:
import pandas as pd
df = pd.DataFrame({"name":["Arun","Priya","Karthik"], "age":[25,32,29], "salary":[50000,80000,60000]})
df

name  age  salary
0     Arun   25   50000
1    Priya   32   80000
2  Karthik   29   60000

In [44]:
import pandas as pd

fileData = pd.read_csv("../datasets/smalldata.csv")
fileData.describe()
fileData.info()

fileData[fileData['salary'] > 60000]
fileData.groupby('dept')['salary'].mean()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   name    5 non-null      object
 1   age     5 non-null      int64 
 2   salary  5 non-null      int64 
 3   dept    5 non-null      object
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes


dept
eng       80000.0
hr        54000.0
mgmt     120000.0
sales     48000.0
Name: salary, dtype: float64

In [ ]:
#scikit-learn

import numpy as np
from sklearn.linear_model import LinearRegression

rng = np.random.RandomState(0)
X = rng.rand(100,1) * 10
y = 3*X.squeeze() + rng.randn(100)*2

model = LinearRegression().fit(X,y)
print(model.predict([[2]]))



[6.41907616]


array([-0.70798782, -2.74990259, -1.28723681, -4.4468063 ,  1.2504629 ,
       -3.20411531, -2.20876668,  0.10433016, -1.47912599,  3.08602919,
       -2.58571382,  0.53410174, -0.07856564, -2.336187  ,  1.04655332,
       -0.34309266,  1.5435811 ,  1.64700831,  4.3264719 ,  2.6730559 ,
       -0.73836368, -0.47875836,  2.19931919,  1.31052746,  1.28026305,
       -3.23391209, -0.04865225, -1.47606182,  0.5598492 , -0.19630078,
        1.82035782,  0.63443643,  1.57265592, -0.93283819, -1.88889251,
       -0.82009939, -0.03404083,  0.75830347,  4.5186179 , -0.0845143 ,
       -1.91189   , -0.69196355, -0.92719195,  0.96296295, -3.08159403,
        0.12652399,  0.31301308,  0.46436207, -1.19463214, -0.47584346,
       -2.84812182, -0.98663977, -1.08572295,  0.83210009, -2.31236486,
        1.5623962 ,  2.98896909, -4.13997005,  0.85251746,  1.35381607,
       -1.27487405, -0.79454363, -0.26576116, -0.59558176, -0.61802594,
       -3.35200761,  2.30466313,  2.15923718, -1.62672852, -2.93

In [16]:
import mlflow as mf

print(mf.VERSION)

3.7.0
